import turtle

def configure_board():
    turtle.pu()
    turtle.ht()
    turtle.setpos(-250,290)
    turtle.pensize(2)
    turtle.pd()
    turtle.fd(500)
    turtle.rt(90)
    turtle.fd(580)
    turtle.rt(90)
    turtle.fd(500)
    turtle.rt(90)
    turtle.fd(580)
    turtle.bk(80)
    turtle.rt(90)
    turtle.fd(2)
    turtle.pensize(5)
    turtle.fd(495)
configure_board()
turtle.mainloop()